#release configuration
#Fri Feb 07 11:55:58 IST 2025
projectVersionPolicyId=default
remoteTagging=true
project.scm.org.jenkins-ci.plugins\:browserstack-integration.tag=HEAD
scm.commentPrefix=[maven-release-plugin] 
completedPhase=end-release
scm.url=scm\:git\:ssh\://git@github.com/jenkinsci/browserstack-integration-plugin.git
project.dev.org.jenkins-ci.plugins\:browserstack-integration=1.2.17-SNAPSHOT
project.scm.org.jenkins-ci.plugins\:browserstack-integration.url=https\://github.com/jenkinsci/browserstack-integration-plugin
project.rel.org.jenkins-ci.plugins\:browserstack-integration=1.2.16
exec.additionalArguments=-DskipTests -Prelease
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=false
project.scm.org.jenkins-ci.plugins\:browserstack-integration.developerConnection=scm\:git\:ssh\://git@github.com/jenkinsci/browserstack-integration-plugin.git
project.scm.org.jenkins-ci.plugins\:browserstack-integration.connection=scm\:git\:ssh\://github.com/jenkinsci/browserstack-integration-plugin.git
scm.tag=browserstack-integration-1.2.16
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean install
